### PR TITLE
Show more post on one page

### PR DESCRIPTION
**Pull request by coot**
Also use `<!-- truncate -->` markers.

### CODE REVIEW

**Comment by coot** [comment]
@hsyl20 it would be nice if the `GHC` updates provided a `TLDR` which ends with `<!-- truncate -->`.

**Comment by hsyl20** [comment]
We likely won't provide a TLDR but we can truncate after the "introduction" (before the first items).

**Comment by hsyl20** [comment]
Truncating just after the "Biweekly update from the GHC DevX team at IOG." should be fine.

**Review by hsyl20 — APPROVED** [review]

**Comment by coot** [comment]
ok, I'll add it to other more recent updates.

**Comment by coot** [comment]
> We likely won't provide a TLDR but we can truncate after the "introduction" (before the first items).

In https://input-output-hk.github.io/cardano-updates we try to provide a high level summary.

**Pull request merged**
